### ISSUE TITLE
Add support for function handlers

### ISSUE THREAD

**Issue by rmeissner** [5afe/safe-core-protocol#47]
It should be possible to register the manager as a fallback handler and register [function handlers](https://github.com/safe-global/safe-core-protocol-specs/blob/main/integrations/README.md#function-handler).

In an initial version function handlers should be registered for a specific function selector.

**Comment by Hasanhli842** [comment]
enhancement

**Comment by akshay-ap** [comment]
Would it mean that `SafeProtocolManager` needs to be added as a Fallbackhandler to Safe?
